/* Copyright (c) 2012-2013 Cheese and Bacon Games, LLC */
/* See the file docs/COPYING.txt for copying permission. */

#ifndef enumerations_h
#define enumerations_h

// AI Decision Types

enum{
    AI_DECISION_NONE,
    AI_DECISION_FOLLOW,
    AI_DECISION_REVIVE,
    AI_DECISION_WANDER,
    AI_DECISION_ITEM
};

//**************************//
// Tile Special Properties: //
//**************************//

enum{
    TILE_SPECIAL_NONE,
    TILE_SPECIAL_CLIMBABLE,
    TILE_SPECIAL_CLIMBABLE_TOP,
    TILE_SPECIAL_HAZARD,
    TILE_SPECIAL_WATER,
    TILE_SPECIAL_MIRROR,
    TILE_SPECIAL_ITEM_HOLDER
};

//***************************//
// Tile Solidity Properties: //
//***************************//

enum{
    TILE_SOLIDITY_BEGIN,
    TILE_SOLIDITY_PASSABLE=TILE_SOLIDITY_BEGIN,
    TILE_SOLIDITY_SOLID,
    TILE_SOLIDITY_CLOUD,
    TILE_SOLIDITY_END
};

//********//
// Items: //
//********//

enum{
    ITEM_BEGIN,
    ITEM_NONE=ITEM_BEGIN,
    ITEM_LEAF,
    ITEM_CHEESE,
    ITEM_AMMO,
    ITEM_SPAWNPOINT,
    ITEM_CHECKPOINT,
    ITEM_ENDPOINT,
    ITEM_SWIMMING_GEAR,
    ITEM_KEY_RED,
    ITEM_KEY_BLUE,
    ITEM_KEY_GREEN,
    ITEM_KEY_YELLOW,
    ITEM_KEY_ORANGE,
    ITEM_KEY_PURPLE,
    ITEM_TOWEL,
    ITEM_SINK,
    ITEM_J_BALLOON,
    ITEM_AMMO_BARREL,
    ITEM_CANDY,
    ITEM_KEY_GRAY,
    ITEM_KEY_BROWN,
    ITEM_KEY_BLACK,
    ITEM_KEY_PINK,
    ITEM_KEY_CYAN,
    ITEM_SUIT_DEADLY_WATER,
    ITEM_SUIT_SHARP,
    ITEM_SUIT_BANANA,
    ITEM_SHOT_HOMING,
    ITEM_TRANSLATOR,
    ITEM_J_WING,
    ITEM_END
};

//*************//
// Door Types: //
//*************//

enum{
    DOOR_TYPE_LOCAL,
    DOOR_TYPE_KEY,
    DOOR_TYPE_STANDARD
};

//*********************//
// Trigger User Types: //
//*********************//

enum{
    TRIGGER_USER_NO_NPC,
    TRIGGER_USER_ALL
};

//****************//
// Spawner Types: //
//****************//

enum{
    SPAWN_ITEM,
    SPAWN_NPC
};

//***************//
// Achievements: //
//***************//

enum{
    ACHIEVEMENT_BEGIN,
    ACHIEVEMENT_COLLECT_ALL_LEAVES_IN_LEVEL=ACHIEVEMENT_BEGIN,
    ACHIEVEMENT_COLLECT_ALL_CHEESE_IN_LEVEL,
    ACHIEVEMENT_PLAY_LEVEL_30_MINUTES,
    ACHIEVEMENT_PLAY_LEVEL_1_HOUR,
    ACHIEVEMENT_PLAY_LEVEL_2_HOURS,
    ACHIEVEMENT_COLLECT_HALF_OF_LEAVES,
    ACHIEVEMENT_COLLECT_HALF_OF_CHEESE,
    ACHIEVEMENT_COLLECT_ALL_LEAVES,
    ACHIEVEMENT_COLLECT_ALL_CHEESE,
    ACHIEVEMENT_KILL_ENEMY_1,
    ACHIEVEMENT_KILL_ENEMY_25,
    ACHIEVEMENT_KILL_ENEMY_50,
    ACHIEVEMENT_KILL_ENEMY_100,
    ACHIEVEMENT_KILL_ENEMY_250,
    ACHIEVEMENT_KILL_ENEMY_500,
    ACHIEVEMENT_KILL_ENEMY_750,
    ACHIEVEMENT_KILL_ENEMY_1000,
    ACHIEVEMENT_ACTIVATE_CHECKPOINT_1,
    ACHIEVEMENT_ACTIVATE_CHECKPOINT_5,
    ACHIEVEMENT_ACTIVATE_CHECKPOINT_10,
    ACHIEVEMENT_ACTIVATE_CHECKPOINT_25,
    ACHIEVEMENT_ACTIVATE_CHECKPOINT_50,
    ACHIEVEMENT_ACTIVATE_CHECKPOINT_75,
    ACHIEVEMENT_ACTIVATE_CHECKPOINT_100,
    ACHIEVEMENT_COLLECT_AMMO_1,
    ACHIEVEMENT_COLLECT_AMMO_10,
    ACHIEVEMENT_COLLECT_AMMO_25,
    ACHIEVEMENT_COLLECT_AMMO_50,
    ACHIEVEMENT_COLLECT_AMMO_100,
    ACHIEVEMENT_COLLECT_AMMO_250,
    ACHIEVEMENT_COLLECT_AMMO_500,
    ACHIEVEMENT_SHOOT_1,
    ACHIEVEMENT_SHOOT_25,
    ACHIEVEMENT_SHOOT_50,
    ACHIEVEMENT_SHOOT_100,
    ACHIEVEMENT_SHOOT_250,
    ACHIEVEMENT_SHOOT_500,
    ACHIEVEMENT_SHOOT_750,
    ACHIEVEMENT_SHOOT_1000,
    ACHIEVEMENT_DIE_1,
    ACHIEVEMENT_DIE_5,
    ACHIEVEMENT_DIE_10,
    ACHIEVEMENT_DIE_25,
    ACHIEVEMENT_DIE_50,
    ACHIEVEMENT_DIE_75,
    ACHIEVEMENT_DIE_100,
    ACHIEVEMENT_DIE_TO_ENEMY_1,
    ACHIEVEMENT_DIE_TO_ENEMY_5,
    ACHIEVEMENT_DIE_TO_ENEMY_10,
    ACHIEVEMENT_DIE_TO_ENEMY_25,
    ACHIEVEMENT_DIE_TO_TRAP_1,
    ACHIEVEMENT_DIE_TO_TRAP_5,
    ACHIEVEMENT_DIE_TO_TRAP_10,
    ACHIEVEMENT_DIE_TO_TRAP_25,
    ACHIEVEMENT_REPLAY_LEVEL_1,
    ACHIEVEMENT_REPLAY_LEVEL_5,
    ACHIEVEMENT_REPLAY_LEVEL_10,
    ACHIEVEMENT_REPLAY_LEVEL_25,
    ACHIEVEMENT_REPLAY_LEVEL_50,
    ACHIEVEMENT_REPLAY_LEVEL_75,
    ACHIEVEMENT_REPLAY_LEVEL_100,
    ACHIEVEMENT_JUMP_1,
    ACHIEVEMENT_JUMP_25,
    ACHIEVEMENT_JUMP_50,
    ACHIEVEMENT_JUMP_100,
    ACHIEVEMENT_JUMP_250,
    ACHIEVEMENT_JUMP_500,
    ACHIEVEMENT_JUMP_750,
    ACHIEVEMENT_JUMP_1000,
    ACHIEVEMENT_PLAY_1_HOUR,
    ACHIEVEMENT_PLAY_2_HOURS,
    ACHIEVEMENT_PLAY_5_HOURS,
    ACHIEVEMENT_PLAY_10_HOURS,
    ACHIEVEMENT_TRAVEL_1_HOUR,
    ACHIEVEMENT_MENUS_1_HOUR,
    ACHIEVEMENT_PULL_LEVER_1,
    ACHIEVEMENT_PULL_LEVER_5,
    ACHIEVEMENT_PULL_LEVER_10,
    ACHIEVEMENT_PULL_LEVER_25,
    ACHIEVEMENT_PULL_LEVER_50,
    ACHIEVEMENT_PULL_LEVER_75,
    ACHIEVEMENT_PULL_LEVER_100,
    ACHIEVEMENT_RIDE_COW_1_SECOND,
    ACHIEVEMENT_RIDE_COW_1_MINUTE,
    ACHIEVEMENT_RIDE_COW_2_MINUTES,
    ACHIEVEMENT_RIDE_COW_3_MINUTES,
    ACHIEVEMENT_RIDE_COW_4_MINUTES,
    ACHIEVEMENT_RIDE_COW_5_MINUTES,
    ACHIEVEMENT_WATER_SHOT_1,
    ACHIEVEMENT_WATER_SHOT_5,
    ACHIEVEMENT_WATER_SHOT_10,
    ACHIEVEMENT_WATER_SHOT_25,
    ACHIEVEMENT_HUBERTS_HOUSE_1_HOUR,
    ACHIEVEMENT_ENTER_WORLDMAP,
    ACHIEVEMENT_ENTER_ANY_LEVEL,
    ACHIEVEMENT_DEFEAT_ALL_BOSSES_BUT_FINAL,
    ACHIEVEMENT_DEFEAT_ALL_BOSSES,
    ACHIEVEMENT_BEAT_ANY_LEVEL,
    ACHIEVEMENT_BEAT_GAME,
    ACHIEVEMENT_BEAT_LEVEL_NO_KILLS,
    ACHIEVEMENT_BEAT_LEVEL_NO_SHOTS,
    ACHIEVEMENT_JOKE_ITEM,
    ACHIEVEMENT_FIRE_50_SHOTS_IN_LEVEL,
    ACHIEVEMENT_MOVE_INVENTORY_ITEM_5,
    ACHIEVEMENT_CHANGE_AN_OPTION,
    ACHIEVEMENT_VIEW_CREDITS,
    ACHIEVEMENT_DIE_AFTER_GOAL,
    ACHIEVEMENT_MAX_DEATH_BOUNCES,
    ACHIEVEMENT_END
};

//***************//
// Window names: //
//***************//

//These need to be in the exact order that the windows are created. See create_windows() in world.cpp.
enum{
    WINDOW_BEGIN,
    WINDOW_MAIN_MENU=WINDOW_BEGIN,
    WINDOW_CREATE_PROFILE,
    WINDOW_CHANGE_PROFILE,
    WINDOW_REWARDS,
    WINDOW_STATS,
    WINDOW_STATS_2,
    WINDOW_ACHIEVEMENTS,
    WINDOW_ACHIEVEMENTS_2,
    WINDOW_ACHIEVEMENTS_3,
    WINDOW_ACHIEVEMENTS_4,
    WINDOW_ACHIEVEMENTS_5,
    WINDOW_ACHIEVEMENTS_6,
    WINDOW_ACHIEVEMENTS_7,
    WINDOW_ACHIEVEMENTS_8,
    WINDOW_OPTIONS,
    WINDOW_OPTIONS_KEYS,
    WINDOW_OPTIONS_KEYS_MP_1,
    WINDOW_OPTIONS_KEYS_MP_2,
    WINDOW_OPTIONS_KEYS_MP_3,
    WINDOW_ABOUT,
    WINDOW_CREDITS,
    WINDOW_HELP,
    WINDOW_HELP_2,
    WINDOW_HELP_3,
    WINDOW_HELP_4,
    WINDOW_HELP_5,
    WINDOW_HELP_6,
    WINDOW_HELP_7,
    WINDOW_HELP_8,
    WINDOW_SOUND_TEST,
    WINDOW_DEMO,
    WINDOW_SELECT_GAME_MODE,
    WINDOW_MP_SETUP,
    WINDOW_SHOW_DATA_LOCATION,
    WINDOW_END
};

//******************************//
// Special information strings: //
//******************************//

enum{
    NO_SPECIAL_INFO,
    SPECIAL_INFO_CURRENT_PROFILE,
    SPECIAL_INFO_NO_PROFILE,
    SPECIAL_INFO_PROFILE_TAKEN,
    SPECIAL_INFO_CREATING_PROFILE,
    SPECIAL_INFO_CHECKBOX_FULLSCREEN,
    SPECIAL_INFO_CHECKBOX_FPS,
    SPECIAL_INFO_CHECKBOX_HOLIDAY_CHEER,
    SPECIAL_INFO_CHECKBOX_TIME_OF_DAY,
    SPECIAL_INFO_CHECKBOX_TIME_OF_DAY_LEVELS,
    SPECIAL_INFO_CHECKBOX_HINTS,
    SPECIAL_INFO_CHECKBOX_MUTE_GLOBAL,
    SPECIAL_INFO_CHECKBOX_MUTE_SOUND,
    SPECIAL_INFO_CHECKBOX_MUTE_MUSIC,
    SPECIAL_INFO_CHECKBOX_HARDWARE_CURSOR,
    SPECIAL_INFO_DIFFICULTY,
    SPECIAL_INFO_VOLUME_GLOBAL,
    SPECIAL_INFO_VOLUME_SOUND,
    SPECIAL_INFO_VOLUME_MUSIC,
    SPECIAL_INFO_KEY_TOGGLE_MAIN_MENU,
    SPECIAL_INFO_KEY_TOGGLE_INVENTORY,
    SPECIAL_INFO_KEY_TOGGLE_MAP,
    SPECIAL_INFO_KEY_SCREENSHOT,
    SPECIAL_INFO_KEY_LEFT,
    SPECIAL_INFO_KEY_UP,
    SPECIAL_INFO_KEY_RIGHT,
    SPECIAL_INFO_KEY_DOWN,
    SPECIAL_INFO_KEY_LOOK,
    SPECIAL_INFO_KEY_JUMP,
    SPECIAL_INFO_KEY_SHOOT,
    SPECIAL_INFO_KEY_CHANGE_CHARACTER,
    SPECIAL_INFO_KEY_PAUSE,
    SPECIAL_INFO_KEY_CHANGE_SHOT,

    SPECIAL_INFO_KEY_1_LEFT,
    SPECIAL_INFO_KEY_1_UP,
    SPECIAL_INFO_KEY_1_RIGHT,
    SPECIAL_INFO_KEY_1_DOWN,
    SPECIAL_INFO_KEY_1_JUMP,
    SPECIAL_INFO_KEY_1_SHOOT,
    SPECIAL_INFO_KEY_1_CHANGE_SHOT,

    SPECIAL_INFO_KEY_2_LEFT,
    SPECIAL_INFO_KEY_2_UP,
    SPECIAL_INFO_KEY_2_RIGHT,
    SPECIAL_INFO_KEY_2_DOWN,
    SPECIAL_INFO_KEY_2_JUMP,
    SPECIAL_INFO_KEY_2_SHOOT,
    SPECIAL_INFO_KEY_2_CHANGE_SHOT,

    SPECIAL_INFO_KEY_3_LEFT,
    SPECIAL_INFO_KEY_3_UP,
    SPECIAL_INFO_KEY_3_RIGHT,
    SPECIAL_INFO_KEY_3_DOWN,
    SPECIAL_INFO_KEY_3_JUMP,
    SPECIAL_INFO_KEY_3_SHOOT,
    SPECIAL_INFO_KEY_3_CHANGE_SHOT,

    SPECIAL_INFO_PROFILE_1,
    SPECIAL_INFO_PROFILE_2,
    SPECIAL_INFO_PROFILE_3,
    SPECIAL_INFO_PROFILE_4,
    SPECIAL_INFO_PROFILE_5,
    SPECIAL_INFO_PROFILE_6,
    SPECIAL_INFO_PROFILE_7,
    SPECIAL_INFO_VERSION,
    SPECIAL_INFO_BUILD_DATE,
    SPECIAL_INFO_MP_PLAYER_0,
    SPECIAL_INFO_MP_PLAYER_1,
    SPECIAL_INFO_MP_PLAYER_2,
    SPECIAL_INFO_MP_PLAYER_3,
    SPECIAL_INFO_MP_PLAYER_TEXT_0,
    SPECIAL_INFO_MP_PLAYER_TEXT_1,
    SPECIAL_INFO_MP_PLAYER_TEXT_2,
    SPECIAL_INFO_MP_PLAYER_TEXT_3,
    SPECIAL_INFO_MP_PLAYER_COUNT,
    SPECIAL_INFO_MP_AI_1,
    SPECIAL_INFO_MP_AI_2,
    SPECIAL_INFO_MP_AI_3,
    SPECIAL_INFO_STAT_PERCENT_COMPLETE,
    SPECIAL_INFO_STAT_LEAVES_COLLECTED,
    SPECIAL_INFO_STAT_CHEESE_COLLECTED,
    SPECIAL_INFO_STAT_ENEMIES_STUNNED,
    SPECIAL_INFO_STAT_CHECKPOINTS_ACTIVATED,
    SPECIAL_INFO_STAT_AMMO_PICKED_UP,
    SPECIAL_INFO_STAT_SHOTS_FIRED,
    SPECIAL_INFO_STAT_TRIGGERS_SHOT,
    SPECIAL_INFO_STAT_ACCURACY,
    SPECIAL_INFO_STAT_DEATHS_TOTAL,
    SPECIAL_INFO_STAT_DEATHS_ENEMIES,
    SPECIAL_INFO_STAT_DEATHS_TRAPS,
    SPECIAL_INFO_STAT_DEATHS_DROWNING,
    SPECIAL_INFO_STAT_LEVELS_REPLAYED,
    SPECIAL_INFO_STAT_TOTAL_JUMPS,
    SPECIAL_INFO_STAT_SECONDS_PLAYING,
    SPECIAL_INFO_STAT_SECONDS_TRAVELING,
    SPECIAL_INFO_STAT_SECONDS_MENUS,
    SPECIAL_INFO_STAT_LEVERS_PULLED,
    SPECIAL_INFO_STAT_SECONDS_RIDING_COWS,
    SPECIAL_INFO_STAT_FARTHEST_FALL,
    SPECIAL_INFO_STAT_WATER_SHOT,
    SPECIAL_INFO_STAT_BOSSES_DEFEATED,
    SPECIAL_INFO_STAT_ITEMS_MOVED,
    SPECIAL_INFO_LEVEL_STAT_LEAVES,
    SPECIAL_INFO_LEVEL_STAT_CHEESE,
    SPECIAL_INFO_LEVEL_STAT_TOTAL_TIME,
    SPECIAL_INFO_LEVEL_STAT_BEST_TIME,
    SPECIAL_INFO_ACHIEVEMENT,
    SPECIAL_INFO_CHECKBOX_ACHIEVEMENT=SPECIAL_INFO_ACHIEVEMENT+ACHIEVEMENT_END,
    SPECIAL_INFO_SHOW_DATA_LOCATION
};

//****************//
// Special input: //
//****************//

enum{
    NO_SPECIAL_INPUT,
    SPECIAL_INPUT_CREATE_PROFILE
};

//*********//
// Colors: //
//*********//

enum{
    COLOR_RAINBOW,

    COLOR_BEGIN,

    COLOR_BLACK=COLOR_BEGIN,

    COLOR_GRAY,

    COLOR_WHITE,

    COLOR_BROWN,
    COLOR_DARK_BROWN,
    COLOR_COPPER,
    COLOR_BRONZE,
    COLOR_SEPIA,
    COLOR_SANDY_BROWN,
    COLOR_WHEAT,
    COLOR_TAN,
    COLOR_PALE_BROWN,
    COLOR_CHAMPAGNE,

    COLOR_YELLOW,
    COLOR_SYSTEM,
    COLOR_GOLD,
    COLOR_YELLOW_PASTEL,
    COLOR_YELLOW_FULL,

    COLOR_ORANGE,
    COLOR_PUMPKIN,
    COLOR_ORANGE_PASTEL,
    COLOR_ORANGE_FULL,

    COLOR_RED,
    COLOR_DARK_RED,
    COLOR_FLAME,
    COLOR_WINE,

    COLOR_PINK,
    COLOR_ROSE,
    COLOR_SHOCKING_PINK,

    COLOR_PURPLE,
    COLOR_VIOLET,
    COLOR_INDIGO,
    COLOR_PURPLE_PASTEL,
    COLOR_PURPLE_FULL,

    COLOR_BLUE,
    COLOR_SKY_BLUE,
    COLOR_UN_BLUE,
    COLOR_BLUE_OCEAN,

    COLOR_GREEN,
    COLOR_JUNGLE,
    COLOR_SPRING,
    COLOR_DARK_GREEN,
    COLOR_GRASS_GREEN,

    COLOR_END
};

//**************//
// Boss States: //
//**************//

enum{
    BOSS_STATE_NOT_SPAWNED,
    BOSS_STATE_SPAWNED,
    BOSS_STATE_DEFEATED
};

//*************//
// Game Modes: //
//*************//

enum{
    GAME_MODE_SP_ADVENTURE,
    GAME_MODE_SP_SURVIVAL,
    GAME_MODE_MP_ADVENTURE,
    GAME_MODE_MP_SURVIVAL,
    GAME_MODE_MP_VERSUS
};

//***************//
// Difficulties: //
//***************//

enum{
    DIFFICULTY_EASY,
    DIFFICULTY_NORMAL,
    DIFFICULTY_HARD
};

//**************//
// Moon Phases: //
//**************//

enum{
    MOON_PHASE_BEGIN,
    MOON_PHASE_NEW=MOON_PHASE_BEGIN,
    MOON_PHASE_WAXING_CRESCENT,
    MOON_PHASE_FIRST_QUARTER,
    MOON_PHASE_WAXING_GIBBOUS,
    MOON_PHASE_FULL,
    MOON_PHASE_WANING_GIBBOUS,
    MOON_PHASE_THIRD_QUARTER,
    MOON_PHASE_WANING_CRESCENT,
    MOON_PHASE_END
};

//***********//
// Holidays: //
//***********//

enum{
    HOLIDAY_NONE,
    HOLIDAY_NEW_YEARS_DAY,
    HOLIDAY_VALENTINES,
    HOLIDAY_ST_PATRICKS,
    HOLIDAY_EASTER,
    HOLIDAY_INDEPENDENCE,
    HOLIDAY_HALLOWEEN,
    HOLIDAY_THANKSGIVING,
    HOLIDAY_CHRISTMAS,
    HOLIDAY_NEW_YEARS_EVE
};

//********//
// Music: //
//********//

enum{
    MUSIC_BEGIN,
    MUSIC_MENU=MUSIC_BEGIN,
    MUSIC_ALARM,
    MUSIC_INTRO1,
    MUSIC_INTRO2,
    MUSIC_INTRO3,
    MUSIC_INTRO4,
    MUSIC_BOSS,
    MUSIC_BOSS_FAST,
    MUSIC_LEVEL_NORMAL,
    MUSIC_LEVEL_WATER,
    MUSIC_WORLDMAP_VALLEY,
    MUSIC_WORLDMAP_CASTLE,
    MUSIC_WORLDMAP_HAUNTED,
    MUSIC_WORLDMAP_MOUNTAIN,
    MUSIC_WORLDMAP_VOLCANO,
    MUSIC_WORLDMAP_DESERT,
    MUSIC_WORLDMAP_OCEAN,
    MUSIC_WORLDMAP_MOUNTAIN_PEAK,
    MUSIC_WORLDMAP_LIGHTHOUSE,
    MUSIC_END
};

//*************************//
// Main World Map Regions: //
//*************************//

enum{
    WORLDMAP_REGION_NORMAL,
    WORLDMAP_REGION_VALLEY,
    WORLDMAP_REGION_CASTLE,
    WORLDMAP_REGION_HAUNTED,
    WORLDMAP_REGION_MOUNTAIN,
    WORLDMAP_REGION_VOLCANO,
    WORLDMAP_REGION_DESERT,
    WORLDMAP_REGION_OCEAN,
    WORLDMAP_REGION_MOUNTAIN_PEAK,
    WORLDMAP_REGION_LIGHTHOUSE
};

//***************//
// Which Window: //
//***************//

enum{
    WHICH_WINDOW_INVENTORY,
    WHICH_WINDOW_MAP,
    WHICH_WINDOW_MESSAGE,
    WHICH_WINDOW_SETUP_SURVIVAL,
    WHICH_WINDOW_SHOP,
    WHICH_WINDOW_UPGRADES,
    WHICH_WINDOW_LEVEL_INFO,
    WHICH_WINDOW_OTHER=WHICH_WINDOW_LEVEL_INFO+16
};

//*****************//
// Save Locations: //
//*****************//

enum{
    SAVE_LOCATION_LOCAL,
    SAVE_LOCATION_HOME
};

//***********//
// Commands: //
//***********//

enum{
    COMMAND_BEGIN,
    COMMAND_TOGGLE_MAIN_MENU=COMMAND_BEGIN,
    COMMAND_TOGGLE_INVENTORY,
    COMMAND_TOGGLE_MAP,
    COMMAND_SCREENSHOT,
    COMMAND_LEFT,
    COMMAND_UP,
    COMMAND_RIGHT,
    COMMAND_DOWN,
    COMMAND_LOOK,
    COMMAND_JUMP,
    COMMAND_SHOOT,
    COMMAND_CHANGE_CHARACTER,
    COMMAND_PAUSE,
    COMMAND_CHANGE_SHOT,
    COMMAND_END
};

//**************//
// Input types: //
//**************//

enum{
    INPUT_TYPE_KEYBOARD,
    INPUT_TYPE_JOYSTICK_BUTTON,
    INPUT_TYPE_JOYSTICK_AXIS,
    INPUT_TYPE_JOYSTICK_HAT,
    INPUT_TYPE_JOYSTICK_BALL
};

//**************************//
// Joystick neutral values: //
//**************************//

enum{
    JOYSTICK_NEUTRAL_NEGATIVE=-24000,
    JOYSTICK_NEUTRAL_POSITIVE=24000
};

//*************//
// Directions: //
//*************//

enum{
    NONE,
    LEFT,
    UP,
    RIGHT,
    DOWN,
    LEFT_UP,
    RIGHT_UP,
    RIGHT_DOWN,
    LEFT_DOWN,
    //This constant is used as a cam_state value, to tell the camera whether it is free or attached to a player.
    CAM_STICKY
};

//*****************//
// Title Movement: //
//*****************//

enum{
    TITLE_BG_MOVING_IN,
    TITLE_BG_MOVING_OUT,
    TITLE_MOVING_IN,
    TITLE_MOVING_OUT,
    TITLE_WAITING,
    TITLE_WAIT_BEFORE_MOVE_OUT,
    TITLE_NOT_MOVING
};

//*************//
// Characters: //
//*************//

enum{
    CHARACTER_BEGIN,
    CHARACTER_HUBERT=CHARACTER_BEGIN,
    CHARACTER_SLIME_O,
    CHARACTER_SKETCH,
    CHARACTER_PENNY,
    CHARACTER_END
};

//*********************//
// Fullscreen Options: //
//*********************//

enum{
    FULLSCREEN_MODE_STANDARD,
    FULLSCREEN_MODE_WINDOWED
};

//********************//
// Button Properties: //
//********************//

enum{
    BUTTON_VISIBLE,
    BUTTON_INVISIBLE
};
enum{
    BUTTON_DISABLED,
    BUTTON_ENABLED
};

#endif
